[package]
name = "convco"
version = "0.3.3"
description = "Conventional commit tools"
keywords = ["conventional", "commit", "changelog", "semantic", "versioning"]
categories = ["development-tools::build-utils"]
readme = "README.md"
homepage = "https://convco.github.io"
repository = "https://github.com/convco/convco.git"
license = "MIT"
authors = ["Hannes De Valkeneer <hannes@de-valkeneer.be>"]
edition = "2018"
exclude = [
    ".*",
]

[dependencies]
chrono = { version = "0.4.15", features = ["serde"] }
git2 = { version = "0.13.8", default-features = false, features = [] }
handlebars = { version = "3.4.0", features = [ "dir_source" ] }
regex = "1.3.9"
semver = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_yaml = "0.8.13"
structopt = "0.3.16"
url = "2.1.1"
dialoguer = "0.6.2"
thiserror = "1.0.22"
skim = "*"

[build-dependencies]
structopt = "0.3.16"

[package.metadata.deb]
depends = ""
extended-description = """\
Conventional commit tools. \
Create a changelog. \
Check if commits follow the convention. \
Calculate the next version based on the conventional commits."""
assets = [
    # bin
    ["target/release/convco", "/usr/local/bin/", "755"],
    # completions
    ["target/completions/convco.bash", "/usr/share/bash-completion/completions/", "644"],
    ["target/completions/_convco", "/usr/share/zsh/vendor-completions/", "644"],
    ["target/completions/convco.fish", "/usr/share/fish/completions/", "644"],
]
