[package]
name = "git-cz"
version = "0.4.0"
description = "Git conventional commit tools written in Rust"
keywords = ["git", "conventional", "commit", "changelog", "semantic", "versioning"]
categories = ["development-tools::build-utils"]
readme = "README.md"
homepage = "https://git-cz.github.io"
repository = "https://github.com/ttys3/git-commitizen.git"
license = "MIT"
authors = ["Hannes De Valkeneer <hannes@de-valkeneer.be>"]
edition = "2018"
exclude = [
    ".*",
]

[dependencies]
chrono = { version = "0.4.15", features = ["serde"] }
git2 = { version = "0.13.8", default-features = false, features = [] }
handlebars = { version = "3.4.0", features = [ "dir_source" ] }
regex = "1.3.9"
semver = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_yaml = "0.8.13"
structopt = "0.3.16"
url = "2.1.1"
dialoguer = "0.6.2"
thiserror = "1.0.22"
skim = "*"
console = "0.14.0"

[build-dependencies]
structopt = "0.3.16"

[package.metadata.deb]
depends = ""
extended-description = """\
Git conventional commit tools written in Rust. \
Create a changelog. \
Check if commits follow the convention. \
Calculate the next version based on the conventional commits."""
assets = [
    # bin
    ["target/release/git-cz", "/usr/local/bin/", "755"],
    # completions
    ["target/completions/git-cz.bash", "/usr/share/bash-completion/completions/", "644"],
    ["target/completions/_git-cz", "/usr/share/zsh/vendor-completions/", "644"],
    ["target/completions/git-cz.fish", "/usr/share/fish/completions/", "644"],
]
